version: '3'
services:
  serviceone:
    image: 'tomcat:9'
    ports:
      - "8090:8080"
    volumes:
      - "/home/ec2-user/docker:/usr/local/tomcat/webapps"

  servicetwo:
    image: 'tomcat:9'
    ports:
      - "8080:8080"  
    volumes:
      - "/home/ec2-user/docker:/usr/local/tomcat/webapps"
